# Generated by Django 5.2.5 on 2026-06-05 12:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_profile_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="activation_token",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
