# Generated by Django 5.2.5 on 2026-07-02 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Resena",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("autor", models.CharField(max_length=100)),
                ("texto", models.TextField()),
                ("rating", models.PositiveSmallIntegerField(default=5)),
                ("foto_url", models.URLField(blank=True, null=True)),
                ("fecha_relativa", models.CharField(blank=True, max_length=50)),
                ("orden", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Reseña",
                "verbose_name_plural": "Reseñas",
                "ordering": ["orden", "-id"],
            },
        ),
    ]
