# Generated by Django 5.2.5 on 2026-07-02 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResenasConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.DecimalField(decimal_places=1, default=4.8, max_digits=2),
                ),
                ("total", models.PositiveSmallIntegerField(default=5)),
                ("ultima_sync", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Configuración de Reseñas",
                "verbose_name_plural": "Configuración de Reseñas",
            },
        ),
    ]
