"""
Django settings for webpersonal project.

Generated by 'django-admin startproject' using Django 3.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import os
from pickle import TRUE

from numpy import True_

#################################################################################

import environ

# Initialise environment variables
env = environ.Env()
# reading .env file
environ.Env.read_env()



# Raises django's ImproperlyConfigured exception if SECRET_KEY not in os.environ
SECRET_KEY = env("SECRET_KEY")

#################################################################################

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/


# SECURITY WARNING: don't run with debug turned on in production!
#DEBUG = True
DEBUG = False

#ALLOWED_HOSTS = []
ALLOWED_HOSTS = ['axxyss.com', 'www.axxyss.com', 'localhost', '127.0.0.1','0.0.0.0']
CSRF_TRUSTED_ORIGINS = ['https://axxyss.com']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
	'django.contrib.sitemaps',
    "django_extensions",
    'django_ckeditor_5',
    'core',
    'pages.apps.PagesConfig',
    'contact',
    'blog',
    'users',
    'categories',
    'comments',
    'portfolio.apps.PortfolioConfig',
    'social.apps.SocialConfig',
    'django_recaptcha',


]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'webpersonal.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'social.processors.ctx_dict',               # agrega la función ctx_dict del archivo processors de la APP social
                 #here add your context Processors
               # 'django.template.context_processors.media',
            ],
        },
    },
]

WSGI_APPLICATION = 'webpersonal.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
         'ENGINE': 'django.db.backends.mysql',
         'NAME': env('ENV_DATABASE_NAME'),
         'USER': env('ENV_DATABASE_USER'),
         'PASSWORD' : env('ENV_DATABASE_PASSWORD'),
         'HOST': env('ENV_DATABASE_SERVER'),  # Generalmente 'localhost' o la IP del servidor
         'PORT': env('ENV_DATABASE_PORT'),  # Puerto predeterminado de MySQL
         'OPTIONS': {
            'charset': 'utf8mb4',  # Recomendado para soporte completo de caracteres
            'use_unicode': True,
            'init_command': "SET time_zone = 'Europe/Madrid'",
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGES = (
    ('es', 'Español'),
    ('en', 'English'),
    ('fr', 'Français'),  # Añadimos el idioma francés
)

LANGUAGE_CODE = 'es'

FILE_CHARSET = 'utf-8'

TIME_ZONE = 'Europe/Madrid'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/


#STATIC_ROOT = '/www/wwwroot/axxyss.com/static/'

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
]

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'


# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CKEDITOR_5_CONFIGS = {
    'default': {
        'toolbar': [
            'heading', '|',
            'bold', 'italic', 'underline', 'strikethrough', 'code', '|',
            'link', 'imageUpload', 'insertTable', '|',
            'bulletedList', 'numberedList', 'todoList', '|',
            'alignment', 'outdent', 'indent', '|',
            'blockQuote', 'codeBlock', '|',
            'undo', 'redo', '|',
            'horizontalLine', 'highlight', 'removeFormat'
        ],
        'language': 'es',
    }
}

CKEDITOR_5_CUSTOM_CSS = 'css/ckeditor_dark.css'


#  Email Config
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
#EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
EMAIL_HOST = env('ENV_EMAIL_HOST')
EMAIL_PORT = 465
EMAIL_USE_SSL = True
#EMAIL_USE_TLS = True
EMAIL_HOST_USER = env('ENV_EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = env('ENV_EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = env('ENV_DEFAULT_FROM_EMAIL')


# Captcha
RECAPTCHA_PUBLIC_KEY = env('ENV_RECAPTCHA_PUBLIC_KEY')
RECAPTCHA_PRIVATE_KEY = env('ENV_RECAPTCHA_PRIVATE_KEY')
#SILENCED_SYSTEM_CHECKS = ['captcha.recaptcha_test_key_error']

SITE_ID = 1

LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'