"""
Django settings for webpersonal project.

Generated by 'django-admin startproject' using Django 3.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import os

from pickle import TRUE

from numpy import True_

from django.utils.translation import gettext_lazy as _

#################################################################################

import environ

# Initialise environment variables
env = environ.Env()
# reading .env file
environ.Env.read_env()



# Raises django's ImproperlyConfigured exception if SECRET_KEY not in os.environ
SECRET_KEY = env("SECRET_KEY")

#################################################################################

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/


# SECURITY WARNING: don't run with debug turned on in production!
#DEBUG = True
DEBUG = True

#ALLOWED_HOSTS = []
ALLOWED_HOSTS = ['axxyss.com', 'www.axxyss.com', 'localhost', '127.0.0.1','0.0.0.0','192.168.1.50','precision.axxyss']


# Application definition

INSTALLED_APPS = [
    'modeltranslation',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites', 
    'django.contrib.sitemaps',
    "django_extensions",
    'django_ckeditor_5',
    'core',
    'pages.apps.PagesConfig',
    'contact',
    'blog',
    'users',
    'categories',
    'comments',
    'portfolio.apps.PortfolioConfig',
    'social.apps.SocialConfig',
    'django_recaptcha',
    'django_countries',


]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


ROOT_URLCONF = 'webpersonal.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'social.processors.ctx_dict',         
            ],
        },
    },
]


WSGI_APPLICATION = 'webpersonal.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
         'ENGINE': 'django.db.backends.mysql',
         'NAME': env('ENV_DATABASE_NAME'),
         'USER': env('ENV_DATABASE_USER'),
         'PASSWORD' : env('ENV_DATABASE_PASSWORD'),
         'HOST': env('ENV_DATABASE_SERVER'),  # Generalmente 'localhost' o la IP del servidor
         'PORT': env('ENV_DATABASE_PORT'),  # Puerto predeterminado de MySQL
         'OPTIONS': {
            'charset': 'utf8mb4',  # Recomendado para soporte completo de caracteres
            'use_unicode': True,
            'init_command': "SET time_zone = 'Europe/Madrid', sql_mode='STRICT_TRANS_TABLES'",
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'es'

FILE_CHARSET = 'utf-8'

TIME_ZONE = 'Europe/Madrid'

USE_I18N = True

USE_L10N = True

USE_TZ = True

PREFIX_DEFAULT_LANGUAGE = False

LANGUAGES = [
    ('es', 'Español'),
    ('en', 'English'),
    ('fr', 'Français'),  
]

# Para la traducción del Blog
MODELTRANSLATION_DEFAULT_LANGUAGE = 'es'
MODELTRANSLATION_LANGUAGES = ('es', 'en', 'fr')

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Diferente ruta de STATIC_ROOT según el entorno (local o servidor)
if DEBUG:
    # Entorno local (desarrollo)
    STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
else:
    # Entorno de producción (servidor Plesk)
    STATIC_ROOT = '/var/www/html/webpersonal/static/'



STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
]

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'



# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Ckeditor
# settings.py

CKEDITOR_5_CONFIGS = {
    'default': {
        'toolbar': [
            'heading', '|',
            'bold', 'italic', 'underline', 'strikethrough', 'code', '|',
            'link', 'imageUpload', 'insertTable', '|',
            'bulletedList', 'numberedList', 'todoList', '|',
            'alignment', 'outdent', 'indent', '|',
            'blockQuote', 'codeBlock', '|',
            'sourceEditing', '|',
            'undo', 'redo', '|',
            'horizontalLine', 'highlight', 'removeFormat'
        ],
        'language': 'es',
    }
}

CKEDITOR_5_CUSTOM_CSS = 'css/ckeditor_dark.css'


# Email Config
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
#EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
EMAIL_HOST = env('ENV_EMAIL_HOST')
EMAIL_PORT = 465
EMAIL_USE_SSL = True
#EMAIL_USE_TLS = True
EMAIL_HOST_USER = env('ENV_EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = env('ENV_EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = env('ENV_DEFAULT_FROM_EMAIL')


# python -m smtpd -n -c DebuggingServer localhost:1025 ------> abrir una terminal con el venv 
# python manage.py runserver_plus --cert-file cert.pem --key-file key.pem   -------> para usa SSL o TLS en entorno de desarrollo

#EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
#EMAIL_HOST = 'localhost'
#EMAIL_HOST_USER = False
#EMAIL_HOST_PASSWORD = False\
#EMAIL_PORT = 1025
#EMAIL_USE_TLS = False
#EMAIL_USE_SSL = False

# Captcha
RECAPTCHA_PUBLIC_KEY = env('ENV_RECAPTCHA_PUBLIC_KEY')
RECAPTCHA_ENTERPRISE_PROJECT_ID = env('ENV_RECAPTCHA_ENTERPRISE_PROJECT_ID')
RECAPTCHA_DEFAULT_SCORE = 0.6 # Puedes ajustarlo entre 0.0 (bot) y 1.0 (humano)
RECAPTCHA_USE_SSL = True
#SILENCED_SYSTEM_CHECKS = ['captcha.recaptcha_test_key_error']

SITE_ID = 1

SILENCED_SYSTEM_CHECKS = [
    'django_recaptcha.recaptcha_test_key_error',
]


LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'


if not DEBUG:
    SECURE_HSTS_SECONDS = 31536000
    SECURE_SSL_REDIRECT = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

# API para las Google Reviews
GOOGLE_PLACES_API_KEY = env('GOOGLE_PLACES_API_KEY')
GOOGLE_PLACE_ID = env('GOOGLE_PLACE_ID')

