# Generated by Django 5.1.2 on 2025-04-04 15:13

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20210524_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='link',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Enlace'),
        ),
        migrations.AlterField(
            model_name='page',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Contenido'),
        ),
    ]
