# Generated by Django 5.1.2 on 2025-04-13 14:09

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_pagetranslation'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagetranslation',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Contenido'),
        ),
    ]
