# Generated by Django 5.1.2 on 2025-04-13 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_pagetranslation_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagetranslation',
            name='link',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Enlace'),
        ),
    ]
