# Generated by Django 5.2.5 on 2026-01-29 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="content_en",
            field=models.TextField(null=True, verbose_name="Contenido"),
        ),
        migrations.AddField(
            model_name="post",
            name="content_es",
            field=models.TextField(null=True, verbose_name="Contenido"),
        ),
        migrations.AddField(
            model_name="post",
            name="content_fr",
            field=models.TextField(null=True, verbose_name="Contenido"),
        ),
        migrations.AddField(
            model_name="post",
            name="title_en",
            field=models.CharField(max_length=200, null=True, verbose_name="Título"),
        ),
        migrations.AddField(
            model_name="post",
            name="title_es",
            field=models.CharField(max_length=200, null=True, verbose_name="Título"),
        ),
        migrations.AddField(
            model_name="post",
            name="title_fr",
            field=models.CharField(max_length=200, null=True, verbose_name="Título"),
        ),
    ]
