# Generated by Django 5.2.5 on 2026-01-30 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_post_content_en_post_content_es_post_content_fr_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="slug_en",
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name="post",
            name="slug_es",
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name="post",
            name="slug_fr",
            field=models.SlugField(null=True, unique=True),
        ),
    ]
