# Generated by Django 5.2.5 on 2026-06-05 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_post_slug_en_post_slug_es_post_slug_fr"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="meta_description",
            field=models.CharField(
                blank=True, max_length=160, verbose_name="Meta descripción"
            ),
        ),
    ]
