# Generated by Django 5.2.5 on 2026-06-05 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_post_meta_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="meta_description_en",
            field=models.CharField(
                blank=True, max_length=160, null=True, verbose_name="Meta descripción"
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="meta_description_es",
            field=models.CharField(
                blank=True, max_length=160, null=True, verbose_name="Meta descripción"
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="meta_description_fr",
            field=models.CharField(
                blank=True, max_length=160, null=True, verbose_name="Meta descripción"
            ),
        ),
    ]
