# Generated by Django 5.1.2 on 2025-04-21 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
    ]
