# Generated by Django 5.2.5 on 2026-08-06 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Conversacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_cliente", models.CharField(db_index=True, max_length=20)),
                ("nombre_cliente", models.CharField(blank=True, max_length=100)),
                ("creada", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Mensaje",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "direccion",
                    models.CharField(
                        choices=[("in", "Entrante"), ("out", "Saliente")], max_length=3
                    ),
                ),
                ("texto", models.TextField()),
                ("creado", models.DateTimeField(auto_now_add=True)),
                (
                    "conversacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mensajes",
                        to="whatsbot.conversacion",
                    ),
                ),
            ],
            options={
                "ordering": ["creado"],
            },
        ),
    ]
