# Generated by Django 5.1.2 on 2025-04-14 15:21

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_project_description_alter_project_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=5)),
                ('title', models.CharField(max_length=200)),
                ('link', models.CharField(blank=True, max_length=200, null=True, verbose_name='Enlace')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Contenido')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='portfolio.project')),
            ],
            options={
                'unique_together': {('project', 'language')},
            },
        ),
    ]
