# Generated by Django 5.1.2 on 2025-04-14 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_projecttranslation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttranslation',
            name='link',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Dirección WEB'),
        ),
    ]
