# Generated by Django 5.1.2 on 2025-04-14 15:34

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_alter_projecttranslation_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projecttranslation',
            name='content',
        ),
        migrations.AddField(
            model_name='projecttranslation',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Descripción'),
        ),
    ]
