# Generated by Django 5.2.5 on 2026-06-04 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0006_remove_projecttranslation_content_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="meta_description",
            field=models.CharField(
                blank=True, max_length=160, verbose_name="Meta descripción"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="slug",
            field=models.SlugField(
                blank=True, max_length=200, unique=True, verbose_name="Slug"
            ),
        ),
        migrations.AddField(
            model_name="projecttranslation",
            name="meta_description",
            field=models.CharField(
                blank=True, max_length=160, verbose_name="Meta descripción"
            ),
        ),
        migrations.AddField(
            model_name="projecttranslation",
            name="slug",
            field=models.SlugField(blank=True, max_length=200, verbose_name="Slug"),
        ),
    ]
