# Generated by Django 5.2.5 on 2026-06-04 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0007_project_meta_description_project_slug_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="slug",
            field=models.SlugField(
                blank=True, max_length=200, null=True, unique=True, verbose_name="Slug"
            ),
        ),
    ]
