# Generated by Django 5.2.5 on 2026-06-15 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0008_alter_project_slug"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={
                "ordering": ["order", "-created"],
                "verbose_name": "proyecto",
                "verbose_name_plural": "proyectos",
            },
        ),
        migrations.AddField(
            model_name="project",
            name="order",
            field=models.PositiveIntegerField(default=0, verbose_name="Orden"),
        ),
    ]
